### ISSUE TITLE
[BUG] Can't get coal

### ISSUE THREAD

**Issue by hvdklauw** [OfficialZygorg/Alchemity#1]
**Describe the bug**
- To get coal I need to mix charcoal in a heater mixer
- For get the mixer heated I need a blaze burner
- To get the blaze burner I need a block of coal.

**To Reproduce**
- To get coal I need to mix charcoal in a heater mixer
- For get the mixer heated I need a blaze burner
- To get the blaze burner I need a block of coal.

**Expected behavior**
Get coal without needing coal

**Modpack version:**
0.0,11

**Additional context**
Maybe need a block of charcoal for the blazeburner instead?

**Comment by OfficialZygorg** [comment]
Update 0.1.1-Release-Testing fixes it :D (Sorry for not seeing this faster)
