### ISSUE TITLE
[BUG] multiple ways to skip the actual clay crafting step

### ISSUE THREAD

**Issue by tyreforhyred** [OfficialZygorg/Alchemity#2]
Just as a heads up there are multiple ways to break the intended progression of actually obtaining clay

Botania Clayconia
Astral Sorcery starlight infusion of sand into clay blocks
Immersive Engineering Mineral Deposits of Silt harvested by the Excavator (which contain clay)
Environmental Tech's Loose Resource Miner give clay blocks (program Flash Memory in a Memory Programmer and put in the miner)
Receiving clay from a Mason Villager while under the Hero of the Village effect  (pillager patrols are possible even without the outposts, they can spawn naturally and thus Raids can be started)

it's possible i may have missed something, thank you for taking the time to read this and it's wonderful to see another pack going for the Ultimate Alchemy style!

**Comment by OfficialZygorg** [comment]
Hi! Thanks for sending a bug report, at the moment, im unable to fix this (formatted the pc, reinstalling the stuff i had, and taking a little break, ill try to drop a bugfix in a few days, on the meantime, please, dont try to get the clay the unintended way.

**Comment by OfficialZygorg** [comment]
Ok, the astral sorcery and botania ways of getting clay are out, but i dont know how to do the rest, as they seem too complex. Going to tag this as cant fully fix

**Comment by OfficialZygorg** [comment]
Please, submit an issue with the feature tag and a code implementation of kubejs if you can fix it (Help is always welcome)

**Comment by liuseniubi** [comment]
Use a datapack for fixing the left problems maybe a better way. (Cuz I don't know how to use KubeJS to edit a non-recipe datapack file XD)
Here is the path:
immersiveengineering/recipes/mineral/silt.json
envirotech/envirotech/resource/overworld/clay.json
minecraft/loot_tables/gameplay/hero_of_the_village/mason_gift.json
(Sorry for my poor grammar)

**Comment by OfficialZygorg** [comment]
Will try tomorrow, as now is late for me

**Comment by OfficialZygorg** [comment]
Not finding on how to remove them, going to keep searching

**Comment by liuseniubi** [comment]
Unzip this file to .minecraft/kubejs/data and the problems should be solved.
[data.zip](https://github.com/OfficialZygorg/Alchemity/files/7847659/data.zip)

**Comment by liuseniubi** [comment]
And I wonder will there a recipe for Menril Sapling?

**Comment by OfficialZygorg** [comment]
Once i reach a mod for the quests, i enable it
Also, if you're going to ask stuff, please, do it on the discord server

**Comment by OfficialZygorg** [comment]
This should be fixed by now then
