### ISSUE TITLE
[BUG] Integrated Tunnels recipe broken for Item Importer.

### ISSUE THREAD

**Issue by StephJ2Fan** [OfficialZygorg/Alchemity#3]
**Describe the bug**
A clear and concise description of what the bug is:
The recipe for the Item Importer is not working. See pictures

**To Reproduce**
(What to do to reproduce the bug/issue)

**Expected behavior**
A clear and concise description of what you expected to happen:
(What should happen)

**Screenshots**
If applicable, add screenshots to help explain your problem:
![recipe it's supposed to be](https://user-images.githubusercontent.com/13186975/152467655-1157143c-43ae-43e9-b89d-539356fd44c6.png)

**Modpack version:**
Version 0.21

**Additional context**
![actual recipe that is not correct](https://user-images.githubusercontent.com/13186975/152467637-03103df0-d588-43b7-8fb1-56c04a0da6bd.png)

**Comment by raresmiron** [comment]
Hi, just downloaded the pack, without this being fixed not sure how I can actually start the pack without cheating the item.
Right now when you use jei recipe for item importer you actually get to craft item exporter so recipe is broken.
